"""Versioned workspace contract surface.

P1 intentionally exposes schemas, canonical encodings, and reference models
only.  Runtime registry mutation, generations, leases, freshness checks, and
workspace commands are implemented by later work packages.
"""

from graphify.workspace.contracts import (
    ADAPTER_CONTRACT_VERSION,
    CANDIDATE_DISTRIBUTION_VERSION,
    CLI_CONTRACT_VERSION,
    ENGINE_BASELINE,
    EXTRACTOR_CACHE_ABI,
    REQUIRED_COMPATIBILITY_ARTIFACTS,
    STATE_SCHEMA_VERSION,
    WORKSPACE_SCHEMA_VERSION,
    UPSTREAM_BASELINE_COMMIT,
    WORKSPACE_SCHEMA_FILES,
    ArtifactManifest,
    CompatibilityManifest,
    CompensationPlan,
    ContractDocument,
    ContractError,
    FencedLease,
    FreshnessRelease,
    GenerationCoordinationLock,
    GenerationReceipt,
    InstallerTransaction,
    JournalEvent,
    OfflineRollback,
    PointerSet,
    PriorPointerRecord,
    Registry,
    UnsupportedContractVersion,
    WorkspaceConfig,
    canonical_json_bytes,
    canonical_sha256,
    decode_journal_frame,
    encode_journal_frame,
    load_schema,
    parse_contract,
    validate_installer_compensation,
)

__all__ = [
    "ADAPTER_CONTRACT_VERSION",
    "CANDIDATE_DISTRIBUTION_VERSION",
    "CLI_CONTRACT_VERSION",
    "ENGINE_BASELINE",
    "EXTRACTOR_CACHE_ABI",
    "REQUIRED_COMPATIBILITY_ARTIFACTS",
    "STATE_SCHEMA_VERSION",
    "WORKSPACE_SCHEMA_VERSION",
    "UPSTREAM_BASELINE_COMMIT",
    "WORKSPACE_SCHEMA_FILES",
    "ArtifactManifest",
    "CompatibilityManifest",
    "CompensationPlan",
    "ContractDocument",
    "ContractError",
    "FencedLease",
    "FreshnessRelease",
    "GenerationCoordinationLock",
    "GenerationReceipt",
    "InstallerTransaction",
    "JournalEvent",
    "OfflineRollback",
    "PointerSet",
    "PriorPointerRecord",
    "Registry",
    "UnsupportedContractVersion",
    "WorkspaceConfig",
    "canonical_json_bytes",
    "canonical_sha256",
    "decode_journal_frame",
    "encode_journal_frame",
    "load_schema",
    "parse_contract",
    "validate_installer_compensation",
]
