"""Versioned workspace contracts plus the bounded P2-P5B2b runtime.

P2 adds external registry persistence, operator-authorized UUID/source
identity, explicit active-source CAS, and fenced leases. P3 adds immutable
generation certification, a framed lifecycle journal, atomic pointers and
recovery, retained coordination locks, explicit capacity policy, and offline
GC. P4 adds one 0.9.16 adapter and two-sided observed-current freshness. P5A
adds the durable semantic queue and stable-watermark certification binding.
P5B1 adds production composition, versioned read-only status, and read-only
doctor. P5B2a adds only explicit operator-authorized initial enrollment and
verified clone/fork adoption through ``graphify workspace register``. P5B2b0
adds internal request-bound staged-build and stale-abandonment recovery. P5B2b
adds provider-neutral ``workspace sync --code-only`` plus truthful staged-build
visibility in status schema v2. P5B2c adds only the one-shot certified
``workspace query --request-stdin`` transport over the existing two-sided
freshness authority. The unnumbered P5B2 identity-maintenance slice adds only
``workspace register rebind`` and ``workspace register rotate``; the unnumbered
active-source slice adds only standalone ``workspace activate``. All remaining
mutation commands, retained query/service operation, installation, and candidate
publication remain deferred.
"""

from graphify.workspace.adapters import (
    AdapterIntent,
    AdapterSelection,
    CompatibilityLane,
    CompatibilityTuple,
    EngineAdapter,
    ObservationTimeout,
    ObservationUnavailable,
    ObservationUnstable,
    ObservationUnsupported,
    QueryRejected,
    QueryRequest,
    SUPPORTED_COMPATIBILITY,
    SourceObservation,
    StructuralBuild,
    UnsupportedCompatibility,
    select_adapter,
)

from graphify.workspace.contracts import (
    ADAPTER_CONTRACT_VERSION,
    CANDIDATE_DISTRIBUTION_VERSION,
    CLI_CONTRACT_VERSION,
    ENGINE_BASELINE,
    EXTRACTOR_CACHE_ABI,
    REQUIRED_COMPATIBILITY_ARTIFACTS,
    STATE_SCHEMA_VERSION,
    WORKSPACE_SCHEMA_VERSION,
    UPSTREAM_BASELINE_COMMIT,
    WORKSPACE_SCHEMA_FILES,
    ArtifactManifest,
    CapacityPolicy,
    CompatibilityManifest,
    CompensationPlan,
    ContractDocument,
    ContractError,
    FencedLease,
    FreshnessRelease,
    GenerationCoordinationLock,
    GenerationReceipt,
    InstallerTransaction,
    JournalEvent,
    JournalFrameTruncated,
    OfflineRollback,
    PointerSet,
    PriorPointerRecord,
    Registry,
    UnsupportedContractVersion,
    WorkspaceConfig,
    canonical_json_bytes,
    canonical_sha256,
    decode_journal_frame,
    encode_journal_frame,
    load_schema,
    parse_contract,
    validate_installer_compensation,
)
from graphify.workspace.identity import (
    AuthorizationError,
    IdentityAction,
    IdentityError,
    OperatorAuthorization,
    SourceAmbiguousError,
    SourceDiscoveryError,
    SourceDiscoveryTimeout,
    SourceIdentity,
    UUIDCollisionError,
    discover_source,
)
from graphify.workspace.leases import (
    LeaseBusy,
    LeaseError,
    LeaseExpired,
    LeaseGrant,
    LeaseIdentityProvider,
    LeaseOwner,
    LeaseRecoveryRequired,
    LeaseStore,
    StaleLease,
    SystemLeaseIdentityProvider,
)
from graphify.workspace.gc import (
    GcError,
    GcPlan,
    GcPlanStale,
    GcProtection,
    GcRecoveryRequired,
    GcStore,
)
from graphify.workspace.generations import (
    CapacityExceeded,
    CertificationRequest,
    GenerationAllocation,
    GenerationConflict,
    GenerationError,
    GenerationStore,
    PayloadChanged,
)
from graphify.workspace.journal import (
    JournalConflict,
    JournalCorrupt,
    JournalError,
    JournalSnapshot,
    JournalStore,
)
from graphify.workspace.persistence import (
    CommitUnknown,
    LockOrderError,
    RuntimeCapabilities,
    StateCorrupt,
    StatePathError,
    UnsupportedRuntime,
    WorkspaceRuntimeError,
)
from graphify.workspace.registry import (
    ActivationResult,
    RegistryError,
    RegistryStore,
    RevisionConflict,
    SourceAlreadyActive,
)
from graphify.workspace.pointers import (
    GenerationRead,
    PointerCAS,
    PointerConflict,
    PointerCorrupt,
    PointerError,
    PointerRecoveryRequired,
    PointerStore,
    PointerSuperseded,
)
from graphify.workspace.freshness import (
    FreshnessAuthority,
    FreshnessResult,
)
from graphify.workspace.semantic_queue import (
    SemanticCapabilityDecision,
    SemanticCapabilityUnavailable,
    SemanticCertificationBlocked,
    SemanticCertificationView,
    SemanticClaim,
    SemanticDesiredWork,
    SemanticQueueCapacityExceeded,
    SemanticQueueConflict,
    SemanticQueueCorrupt,
    SemanticQueueError,
    SemanticQueueItem,
    SemanticQueuePolicy,
    SemanticQueueSnapshot,
    SemanticQueueStore,
    StaleSemanticClaim,
    decide_semantic_capability,
)
from graphify.workspace.composition import (
    RUNTIME_AUTHORITY_CONTRACT,
    RUNTIME_AUTHORITY_FILENAME,
    RUNTIME_AUTHORITY_FORMAT_VERSION,
    WorkspaceAuthorityError,
    WorkspaceAuthorityInvalid,
    WorkspaceAuthorityUnsupported,
    WorkspaceRuntime,
    WorkspaceRuntimeAuthority,
    WorkspaceRuntimeInputs,
    compose_workspace_runtime,
    load_workspace_runtime_inputs,
)
from graphify.workspace.status import (
    EXIT_DEGRADED,
    EXIT_INVALID,
    EXIT_READY,
    EXIT_USAGE,
    STATUS_CONTRACT,
    STATUS_SCHEMA_VERSION,
    WorkspaceStatusReport,
    inspect_workspace_status,
    load_status_schema,
)
from graphify.workspace.sync import (
    SYNC_MODE,
    SYNC_RECEIPT_CONTRACT,
    SYNC_REQUEST_CONTRACT,
    SYNC_REQUEST_MAX_BYTES,
    SYNC_SCHEMA_VERSION,
    StagedBuildRecoveryRequired,
    SyncAuthorityConflict,
    SyncLeaseBusy,
    SyncReceipt,
    SyncRequest,
    SyncRequestInvalid,
    WorkspaceSyncError,
    synchronize_code_only,
)

__all__ = [
    "ADAPTER_CONTRACT_VERSION",
    "AdapterIntent",
    "AdapterSelection",
    "CANDIDATE_DISTRIBUTION_VERSION",
    "CLI_CONTRACT_VERSION",
    "ENGINE_BASELINE",
    "EXIT_DEGRADED",
    "EXIT_INVALID",
    "EXIT_READY",
    "EXIT_USAGE",
    "EXTRACTOR_CACHE_ABI",
    "REQUIRED_COMPATIBILITY_ARTIFACTS",
    "RUNTIME_AUTHORITY_CONTRACT",
    "RUNTIME_AUTHORITY_FILENAME",
    "RUNTIME_AUTHORITY_FORMAT_VERSION",
    "STATE_SCHEMA_VERSION",
    "STATUS_CONTRACT",
    "STATUS_SCHEMA_VERSION",
    "SYNC_MODE",
    "SYNC_RECEIPT_CONTRACT",
    "SYNC_REQUEST_CONTRACT",
    "SYNC_REQUEST_MAX_BYTES",
    "SYNC_SCHEMA_VERSION",
    "WORKSPACE_SCHEMA_VERSION",
    "UPSTREAM_BASELINE_COMMIT",
    "WORKSPACE_SCHEMA_FILES",
    "ArtifactManifest",
    "CapacityExceeded",
    "CapacityPolicy",
    "ActivationResult",
    "AuthorizationError",
    "CompatibilityManifest",
    "CompatibilityLane",
    "CompatibilityTuple",
    "CompensationPlan",
    "CommitUnknown",
    "ContractDocument",
    "ContractError",
    "EngineAdapter",
    "FencedLease",
    "FreshnessRelease",
    "FreshnessAuthority",
    "FreshnessResult",
    "GenerationCoordinationLock",
    "GenerationAllocation",
    "GenerationConflict",
    "GenerationError",
    "GenerationRead",
    "GenerationReceipt",
    "GenerationStore",
    "CertificationRequest",
    "GcError",
    "GcPlan",
    "GcPlanStale",
    "GcProtection",
    "GcRecoveryRequired",
    "GcStore",
    "InstallerTransaction",
    "IdentityAction",
    "IdentityError",
    "JournalEvent",
    "JournalConflict",
    "JournalCorrupt",
    "JournalError",
    "JournalFrameTruncated",
    "JournalSnapshot",
    "JournalStore",
    "LeaseBusy",
    "LeaseError",
    "LeaseExpired",
    "LeaseGrant",
    "LeaseIdentityProvider",
    "LeaseOwner",
    "LeaseRecoveryRequired",
    "LeaseStore",
    "LockOrderError",
    "OfflineRollback",
    "OperatorAuthorization",
    "ObservationTimeout",
    "ObservationUnavailable",
    "ObservationUnstable",
    "ObservationUnsupported",
    "PayloadChanged",
    "PointerCAS",
    "PointerConflict",
    "PointerCorrupt",
    "PointerError",
    "PointerRecoveryRequired",
    "PointerSet",
    "PointerStore",
    "PointerSuperseded",
    "QueryRejected",
    "QueryRequest",
    "PriorPointerRecord",
    "Registry",
    "RegistryError",
    "RegistryStore",
    "RevisionConflict",
    "SourceAlreadyActive",
    "RuntimeCapabilities",
    "SemanticCapabilityDecision",
    "SemanticCapabilityUnavailable",
    "SemanticCertificationBlocked",
    "SemanticCertificationView",
    "SemanticClaim",
    "SemanticDesiredWork",
    "SemanticQueueCapacityExceeded",
    "SemanticQueueConflict",
    "SemanticQueueCorrupt",
    "SemanticQueueError",
    "SemanticQueueItem",
    "SemanticQueuePolicy",
    "SemanticQueueSnapshot",
    "SemanticQueueStore",
    "SourceAmbiguousError",
    "SourceDiscoveryError",
    "SourceDiscoveryTimeout",
    "SourceIdentity",
    "SourceObservation",
    "StructuralBuild",
    "SUPPORTED_COMPATIBILITY",
    "StaleSemanticClaim",
    "StaleLease",
    "SystemLeaseIdentityProvider",
    "StateCorrupt",
    "StatePathError",
    "UnsupportedContractVersion",
    "UnsupportedCompatibility",
    "UnsupportedRuntime",
    "UUIDCollisionError",
    "WorkspaceConfig",
    "WorkspaceRuntime",
    "WorkspaceRuntimeAuthority",
    "WorkspaceAuthorityError",
    "WorkspaceAuthorityInvalid",
    "WorkspaceAuthorityUnsupported",
    "WorkspaceRuntimeInputs",
    "WorkspaceRuntimeError",
    "WorkspaceStatusReport",
    "WorkspaceSyncError",
    "StagedBuildRecoveryRequired",
    "SyncAuthorityConflict",
    "SyncLeaseBusy",
    "SyncReceipt",
    "SyncRequest",
    "SyncRequestInvalid",
    "canonical_json_bytes",
    "canonical_sha256",
    "compose_workspace_runtime",
    "load_workspace_runtime_inputs",
    "decide_semantic_capability",
    "decode_journal_frame",
    "discover_source",
    "encode_journal_frame",
    "inspect_workspace_status",
    "load_schema",
    "load_status_schema",
    "parse_contract",
    "select_adapter",
    "synchronize_code_only",
    "validate_installer_compensation",
]
